from evdplanner.rs.linalg import Vec3

class Mat4:
    data: list[float]
    def __init__(self): ...
    @staticmethod
    def identity() -> "Mat4": ...
    @staticmethod
    def translation(x: float, y: float, z: float) -> "Mat4": ...
    @staticmethod
    def scale(x: float, y: float, z: float) -> "Mat4": ...
    @staticmethod
    def rotation(axis: Vec3, angle: float) -> "Mat4": ...
    def transpose(self) -> "Mat4": ...
    def __len__(self): ...
    def __getitem__(self, item: tuple[int, int]) -> float: ...
    def __setitem__(self, key, value) -> None: ...
    def __add__(self, other: "Mat4") -> "Mat4": ...
    def __iadd__(self, other: "Mat4") -> "Mat4": ...
    def __sub__(self, other: "Mat4") -> "Mat4": ...
    def __isub__(self, other: "Mat4") -> "Mat4": ...
    def __mul__(self, other: "Mat4" | Vec3 | float) -> "Mat4": ...
    def __imul__(self, other: "Mat4" | Vec3 | float) -> "Mat4": ...
