[project]
name = "evdmeshlib"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy~=1.26.0",
    "taichi~=1.6.0"
]

[build-system]
requires = ["maturin>=1.0, <2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "evdmeshlib._rs"
features = ["pyo3/extension-module"]
