from evdplanner.rs import Ray, Vec3

class Aabb:
    min: Vec3
    max: Vec3

    def __init__(self) -> None: ...
    def intersect(self, ray: Ray, epsilon: float = 1e-8) -> bool: ...
    def grow(self, v: Vec3) -> None: ...
    @property
    def longest_axis(self) -> int: ...
